services:
  sql-dev:
    container_name: sql-dev
    build:
      context: .
    volumes:
      - ./mssql-certs:/var/opt/mssql/certs
      - ./mssql-certs/mssql.conf:/var/opt/mssql/mssql.conf
      - ./backups:/var/opt/mssql/backup
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
      SQL_LOGIN: ${SQL_LOGIN}
      SQL_PASSWORD: ${SQL_PASSWORD}
      MSSQL_TLS_PFX: /var/opt/mssql/certs/mssql.pfx
      MSSQL_TLS_PFX_PASSWORD: ${PFX_PASSWORD}
      ALLOWED_IPS: ${ALLOWED_IPS}
    ports:
          - "${HOST_PORT:-1433}:1433"
    cap_add:
          - NET_ADMIN
    restart: unless-stopped
